name: folder_sync
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2


  path_provider: ^2.1.1
  file_picker: ^10.1.9
  permission_handler: ^11.3.1  


  nearby_connections: ^4.3.0
  connectivity_plus: ^6.0.1


  app_settings: ^6.1.1


  provider: ^6.1.1

  # UI components
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  # For handling file operations
  mime: ^1.0.4
  crypto: ^3.0.3
  path: ^1.8.3
  
  intl: ^0.19.0
  multicast_dns: ^0.3.3
  
  # WiFi Direct P2P connection
  flutter_p2p_connection: ^3.0.0
  
  # File viewing packages
  syncfusion_flutter_pdfviewer: ^27.1.48
  photo_view: ^0.14.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  open_filex: ^4.3.4
  share_plus: ^7.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"